Update dev-build.yml

diff --git a/.github/workflows/dev-build.yml b/.github/workflows/dev-build.yml
--- a/.github/workflows/dev-build.yml
+++ b/.github/workflows/dev-build.yml
@@ -9,6 +9,15 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
+        
+      - name: Check if PAT_TOKEN exists
+        run: |
+          if [ -z "${{ secrets.PAT_TOKEN }}" ]; then
+            echo "PAT_TOKEN is missing. Exiting..."
+            exit 1
+          else
+            echo "PAT_TOKEN is set."
+          fi
 
       - name: Pull latest production subtree
         run: |
@@ -89,11 +98,7 @@ jobs:
           git config --local user.email "github-actions[bot]@users.noreply.github.com"
           git config --local user.name "GitHub Actions"
           git add -A  # Stages all new, modified, and deleted files
-          if git diff-index --quiet HEAD; then
-            echo "No changes to commit"
-          else
-            git commit -m "Automated extraction and SCSS compilation"
-            git push "https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/msarson/discourse-dev-highlight-clarion.git" HEAD:master
-          fi
+          git commit -m "Automated extraction and SCSS compilation"
+          git push "https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/msarson/discourse-dev-highlight-clarion.git" HEAD:master
         
         
